name: balanceteshaters

services:
  db:
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      timeout: 2s
  api:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    networks:
      - default
      - d4g-internal
    env_file: .env
    environment:
      - BTH_ENGINE_ECHO=${BTH_ENGINE_ECHO}
      - BTH_LOGGING_CONFIGURATION_FILE=${BTH_LOGGING_CONFIGURATION_FILE}
      - BTH_PG_DSN=${BTH_PG_DSN}
      - BTH_PRIVATE_API_TOKEN=${BTH_PRIVATE_API_TOKEN}
      - BTH_PUBLIC_API_TOKEN=${BTH_PUBLIC_API_TOKEN}
    ports:

      - "${BTH_API_PORT:-8001}:8000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "${BTH_CPU_LIMIT:-4.0}"
          memory: "${BTH_MEMORY_LIMIT:-3G}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.balanceteshaters-app.rule=Host(`balanceteshaters-app.services.d4g.fr`)
      - traefik.http.routers.balanceteshaters-app.entryPoints=webtls
      - traefik.http.routers.balanceteshaters-app.tls=true
      - traefik.docker.network=d4g-internal
      - traefik.http.services.balanceteshaters-app.loadbalancer.server.port=8000

networks:
  d4g-internal:
    external: true
