name: CleverCloud deployment

on:
  pull_request:
  push:
    branches: [main]

jobs:
  - name: Deploy backend app
    uses: CleverCloud/clever-cloud-review-app@v2.0.2
    env:
      CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
      ORGA_ID: ${{ secrets.ORGA_ID }}
    with:
      type: 'docker'
