name: CleverCloud deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy backend app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: 47ng/actions-clever-cloud@v2.1.0
        with:
          alias: 'BTH'
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}