name: Web Extension

on:
  pull_request:
  push:
    branches: [main]
    tags:
      # Tags named webext-v** will trigger Web extension release creation
      - webext-v**

jobs:
  extension-checks:
    name: Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-extension
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Complie
        run: pnpm compile

      - name: Format
        run: pnpm format:check

      - name: Test
        run: pnpm test

  extension-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-extension
    outputs:
      version-name: ${{steps.compute-version.outputs.version-name}}
      tag-version: ${{steps.compute-version.outputs.tag-version}}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Calculate Extension Version
        id: compute-version
        run: |
          SHA=${GITHUB_SHA::7}
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then            
            WEBEXT_VERSION_NAME="0.0.0-dev-pr${{ github.event.number }}-$SHA"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            # Strips 'webext-v' prefix to result in 'x.y.z-sha'
            WEBEXT_TAG_VERSION=${GITHUB_REF_NAME#webext-v}
            WEBEXT_VERSION_NAME="$WEBEXT_TAG_VERSION-$SHA"
          else
            WEBEXT_VERSION_NAME="0.0.0-dev-latest-$SHA"
          fi
          echo "version-name=$WEBEXT_VERSION_NAME" >> $GITHUB_OUTPUT
          echo "tag-version=$WEBEXT_TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Set version in package.json
        run: |
          echo "Using package version: ${{steps.compute-version.outputs.version-name}}" 
          jq --arg ver "${{steps.compute-version.outputs.version-name}}" '.version = $ver' package.json > tmp.json && mv tmp.json package.json

      - name: Build extension zip
        env:
          # Inject the VITE_BACKEND_API_TOKEN.
          VITE_BACKEND_API_TOKEN: ${{ secrets.VITE_BACKEND_API_TOKEN }}
        run: pnpm zip

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        id: upload-bth-extension-artifact
        with:
          if-no-files-found: error
          name: bth-extension-chrome
          # needed because files are in a .output folder
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/browser-extension/.output/chrome-mv3
          retention-days: 30

      - name: "[PR] Link artifacts in PR"
        if: github.event_name == 'pull_request' && steps.upload-bth-extension-artifact.outcome == 'success'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            📦 Web extension build artifacts: ${{ steps.upload-bth-extension-artifact.outputs.artifact-url }}
          comment-tag: extension-artifacts

      - name: "[main] Copy assets named bth-extension"
        if: github.ref == 'refs/heads/main'
        run: |
          cp .output/bth-extension-*-chrome.zip .output/bth-extension-latest-chrome.zip

      - name: "[main] Update assets on extension-latest release"
        uses: softprops/action-gh-release@v2.5.0
        if: github.ref == 'refs/heads/main'
        with:
          name: Web Extension Latest Development Build
          tag_name: extension-latest
          target_commitish: ${{github.sha}}
          prerelease: true
          fail_on_unmatched_files: true
          files: ${{github.workspace}}/browser-extension/.output/bth-extension-latest*.zip

  publish:
    name: Publish Release To Store
    needs: [extension-checks, extension-artifacts]
    if: (github.ref_type == 'tag' && startsWith(github.ref_name, 'webext-v'))
    runs-on: ubuntu-latest
    environment: Chrome Web Store
    permissions:
      contents: "write"
      id-token: "write"
    defaults:
      run:
        working-directory: browser-extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: "Download extension artifact"
        uses: actions/download-artifact@v8
        with:
          name: bth-extension-chrome
          skip-decompress: true
          path: browser-extension
      - name: Check Zip
        run: |
          echo "Check zip integrity"
          unzip -t bth-extension-chrome.zip
      - name: "Create GH release"
        id: create-tag-release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Web Extension ${{needs.extension-artifacts.outputs.tag-version}}
          fail_on_unmatched_files: true
          files: browser-extension/bth-extension-chrome.zip
      - name: "GCP Authentication"
        uses: "google-github-actions/auth@v3"
        id: gcp-auth
        with:
          service_account: ${{secrets.CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL}}
          workload_identity_provider: "projects/476322675150/locations/global/workloadIdentityPools/github"
          token_format: "access_token"
      - name: Test API access
        env:
          EXTENSION_ID: "bjmmakmdjbdlhghmjobpcnmeefhfajfe"
          PUBLISHER_ID: "2391fb02-9ced-4094-9aa6-b33d4e554064"
          ACCESS_TOKEN: ${{steps.gcp-auth.outputs.access_token}}
        run: |
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -X GET https://chromewebstore.googleapis.com/v2/publishers/${PUBLISHER_ID}/items/${EXTENSION_ID}:fetchStatus

      - name: "Submit to Chrome Web Store"
        env:
          CHROME_API_VERSION: "v2"
          CHROME_EXTENSION_ID: "bjmmakmdjbdlhghmjobpcnmeefhfajfe"
          CHROME_PUBLISHER_ID: "2391fb02-9ced-4094-9aa6-b33d4e554064"
          CHROME_PUBLISH_TYPE: "DEFAULT_PUBLISH"
          CHROME_SERVICE_ACCOUNT_ACCESS_TOKEN: ${{steps.gcp-auth.outputs.access_token}}
        run: pnpm publish-extension ${{case(contains(github.ref_name, 'debug-publish'), '--dry-run', '')}} --chrome-zip bth-extension-chrome.zip

  e2e-tests:
    name: E2E Tests
    defaults:
      run:
        working-directory: browser-extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "browser-extension/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version-file: "browser-extension/package.json"
          cache-dependency-path: "browser-extension/pnpm-lock.yaml"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium
      - name: Build extension
        run: pnpm build
        env:
          # Enable degraded scrapping to still scrap even if some data is missing due to bot suspicieon
          VITE_YT_ALLOW_DEGRADED_SCRAPPING: true

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run E2E tests
        working-directory: ./browser-extension
        env:
          PATH_TO_EXTENSION: ../.output/chrome-mv3
        run: CI=true xvfb-run pnpm playwright test --retries=3

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: browser-extension/playwright-report/
          retention-days: 5
